# Generated by Django 3.2.13 on 2022-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewerPipeBoxInfo',
            fields=[
                ('idn', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='하수관로 고유번호')),
                ('box_height', models.FloatField(verbose_name='박스 높이')),
            ],
        ),
    ]
