# Generated by Django 3.2.13 on 2022-07-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_sewerpipeboxinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewerpipe',
            name='idn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_info', to='data.sewerpipeboxinfo'),
        ),
    ]
